<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Batch extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'batches';

    protected $fillable = [
        'quantity',
        'unit_cost',
        'product_id',
        'provider_id',
        'unit',
        'sku'
    ];

    /*********** Methods ************/

    /********** End Methods *********/


    /*********** Relations ************/


    /********** End Relations *********/


    /*********** Appends ************/


    /********** End Appends *********/

    // BOOT
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            Log::create([
                "category" => "Productos",
                "action" => "Se creó el producto " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::updated(function ($model) {

            Log::create([
                "category" => "Productos",
                "action" => "Se actualizó el producto " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::deleted(function ($model) {

            Log::create([
                "category" => "Productos",
                "action" => "Se eliminó el producto " . $model->name,
                "user_id" => Auth::id()
            ]);
        });
    }
}
