<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Batch extends Model
{
    use HasFactory, SoftDeletes;

    protected $STATUS = [
        0 => 'Almacenado',
        1 => 'Activo',
        2 => 'Terminado',
        3 => 'Perdida'
    ];

    protected $table = 'batches';

    protected $fillable = [
        'quantity',
        'unit_cost',
        'product_id',
        'provider_id'
    ];

    /*********** Methods ************/

    /********** End Methods *********/


    /*********** Relations ************/

    public function product()
    {
        return $this->belongsTo(Product::class);
    }

    public function provider()
    {
        return $this->belongsTo(Provider::class);
    }

    /********** End Relations *********/


    /*********** Appends ************/

    public function getProductNameAttribute()
    {
        return $this->product->name ?? '';
    }

    public function getProviderNameAttribute()
    {
        return $this->provider->name ?? '';
    }

    public function getStatusNameAttribute()
    {
        return $this->STATUS[$this->status] ?? '';
    }

    /********** End Appends *********/

    // BOOT
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            Log::create([
                "category" => "Lotes",
                "action" => "Se creó el lote " . $model->sku,
                "user_id" => Auth::id()
            ]);
        });

        static::updated(function ($model) {

            Log::create([
                "category" => "Lotes",
                "action" => "Se actualizó el lote " . $model->sku,
                "user_id" => Auth::id()
            ]);
        });

        static::deleted(function ($model) {

            Log::create([
                "category" => "Lotes",
                "action" => "Se eliminó el lote " . $model->sku,
                "user_id" => Auth::id()
            ]);
        });
    }
}
