<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Incident extends Model
{
    use HasFactory, SoftDeletes;

    public $STATUSES = [
        1 => "No atendida",
        2 => "En proceso",
        3 => "Completada",
        4 => "Rechazada"
    ];

    protected $table = 'incidents';

    protected $fillable = [
        'subject',
        'description',
        'employee_id',
        'incident_type_id'
    ];

    /*********** Methods ************/

    /********** End Methods *********/


    /*********** Relations ************/

    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }

    /**
     * Get incident type
     */
    public function incident_type()
    {
        return $this->belongsTo(IncidentType::class);
    }

    /********** End Relations *********/


    /*********** Appends ************/

    // Get the employee number of employee
    public function getEmployeeNumberAttribute()
    {
        return $this->employee->employee_number ?? '';
    }

    // Get the name of employee
    public function getEmployeeNameAttribute()
    {
        return $this->employee->name ?? '';
    }

    public function getStatusNameAttribute()
    {
        return $this->STATUSES[$this->status];
    }

    /********** End Appends *********/

    // BOOT
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            Log::create([
                "category" => "Incidencias",
                "action" => "Se creó la incidencia " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::deleted(function ($model) {

            Log::create([
                "category" => "Incidencias",
                "action" => "Se eliminó la incidencia " . $model->name,
                "user_id" => Auth::id()
            ]);
        });
    }
}
