<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Product extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'products';

    protected $fillable = [
        'name',
        'product_type_id',
        'description'
    ];

    /*********** Methods ************/

    /********** End Methods *********/


    /*********** Relations ************/

    public function product_type(): BelongsTo
    {
        return $this->belongsTo(ProductType::class);
    }

    public function providers()
    {
        return $this->belongsToMany(Provider::class);
    }

    /********** End Relations *********/


    /*********** Appends ************/

    public function getProductTypeNameAttribute()
    {
        return $this->product_type->name ?? '';
    }

    /********** End Appends *********/

    // BOOT
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            Log::create([
                "category" => "Producto",
                "action" => "Se creó el producto " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::updated(function ($model) {

            Log::create([
                "category" => "Producto",
                "action" => "Se actualizó el producto " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::deleted(function ($model) {

            Log::create([
                "category" => "Producto",
                "action" => "Se eliminó el producto " . $model->name,
                "user_id" => Auth::id()
            ]);
        });
    }
}
