<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Auth;

class ProductType extends Model
{
    use HasFactory;

    protected $table = 'product_types';

    protected $fillable = [
        'name'
    ];


    /*********** Methods ************/

    /********** End Methods *********/


    /*********** Relations ************/

    public function products(): HasMany
    {
        return $this->hasMany(Product::class);
    }

    /********** End Relations *********/

    // BOOT
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            Log::create([
                "category" => "Tipos de producto",
                "action" => "Se creó el tipo de producto " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::updated(function ($model) {

            Log::create([
                "category" => "Tipos de producto",
                "action" => "Se actualizó el tipo de producto " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::deleted(function ($model) {

            Log::create([
                "category" => "Tipos de producto",
                "action" => "Se eliminó el tipo de producto " . $model->name,
                "user_id" => Auth::id()
            ]);
        });
    }
}
