<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Provider extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'providers';

    protected $fillable = [
        'name',
        'address',
        'email',
        'phone_number',
        'schedule',
        'business_name',
        'contact_job',
        'contact_name',
        'bank_account',
        'bank',
        'payment_form_id',
        'credit',
        'max_purchase_allowed',
        'is_producer'
    ];

    /*********** Methods ************/

    /********** End Methods *********/


    /*********** Relations ************/

    public function products()
    {
        return $this->belongsToMany(Product::class)->withPivot('price');
    }

    public function payment_form()
    {
        return $this->belongsTo(PaymentForm::class);
    }


    /********** End Relations *********/


    /*********** Appends ************/


    /********** End Appends *********/

    // BOOT
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            Log::create([
                "category" => "Proveedor",
                "action" => "Se creó el proveedor " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::updated(function ($model) {

            Log::create([
                "category" => "Proveedor",
                "action" => "Se actualizó el proveedor " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::deleted(function ($model) {

            Log::create([
                "category" => "Proveedor",
                "action" => "Se eliminó el proveedor " . $model->name,
                "user_id" => Auth::id()
            ]);
        });
    }
}
