<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Provider extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'providers';

    protected $fillable = [
        'name',
        'address',
        'contact',
        'email',
        'phone_number',
        'schedule'
    ];

    /*********** Methods ************/

    /********** End Methods *********/


    /*********** Relations ************/

    public function products()
    {
        return $this->belongsToMany(Product::class)->withPivot('price');
    }

    /********** End Relations *********/


    /*********** Appends ************/


    /********** End Appends *********/

    // BOOT
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            Log::create([
                "category" => "Proveedor",
                "action" => "Se creó el proveedor " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::updated(function ($model) {

            Log::create([
                "category" => "Proveedor",
                "action" => "Se actualizó el proveedor " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::deleted(function ($model) {

            Log::create([
                "category" => "Proveedor",
                "action" => "Se eliminó el proveedor " . $model->name,
                "user_id" => Auth::id()
            ]);
        });
    }
}
