<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Unit extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'units';

    protected $fillable = [
        'name'
    ];

    /*********** Methods ************/

    /********** End Methods *********/


    /*********** Relations ************/

    public function inventories()
    {
        return $this->belongsToMany(Inventory::class);
    }

    /********** End Relations *********/


    /*********** Appends ************/

    /********** End Appends *********/

    // BOOT
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            Log::create([
                "category" => "Unidad",
                "action" => "Se creó la unidad " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::updated(function ($model) {

            Log::create([
                "category" => "Inventarios",
                "action" => "Se actualizó la unidad " . $model->name,
                "user_id" => Auth::id()
            ]);
        });

        static::deleted(function ($model) {

            Log::create([
                "category" => "Inventarios",
                "action" => "Se eliminó la unidad " . $model->name,
                "user_id" => Auth::id()
            ]);
        });
    }
}
