<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Vehicle extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'vehicles';

    protected $fillable = [
        'license_plate',
        'brand',
        'description',
        'vehicle_type_id',
        'employee_id'
    ];
    /**
     * @var mixed
     */

    /*********** Methods ************/



    /********** End Methods *********/


    /*********** Relations ************/

    public function vehicle_type(): BelongsTo
    {
        return $this->belongsTo(VehicleType::class);
    }

    public function mileage_records()
    {
        return $this->hasMany(MileageRecord::class);
    }

    public function employee()
    {
        return $this->belongsTo(Employee::class);
    }

    /********** End Relations *********/


    /*********** Appends ************/

    public function getVehicleTypeNameAttribute()
    {
        return $this->vehicle_type->name ?? '';
    }

    public function getDriverNameAttribute()
    {
        return $this->employee->user->name ?? '';
    }

    /********** End Appends *********/

    // BOOT
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($model) {
            Log::create([
                "category" => "Vehiculos",
                "action" => "Se creó el vehiculo " . $model->license_plate,
                "user_id" => Auth::id()
            ]);
        });

        static::updated(function ($model) {

            Log::create([
                "category" => "Vehiculos",
                "action" => "Se actualizó el vehiculo " . $model->license_plate,
                "user_id" => Auth::id()
            ]);
        });

        static::deleted(function ($model) {

            Log::create([
                "category" => "Vehiculos",
                "action" => "Se eliminó el vehiculo " . $model->license_plate,
                "user_id" => Auth::id()
            ]);
        });
    }
}
