<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Vehicle extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'vehicles';

    protected $fillable = [
        'license_plate',
        'brand',
        'description',
        'vehicle_type_id'
    ];
    /**
     * @var mixed
     */

    /*********** Methods ************/



    /********** End Methods *********/


    /*********** Relations ************/

    public function vehicle_type(): BelongsTo
    {
        return $this->belongsTo(VehicleType::class);
    }

    public function driver(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(Driver::class);
    }

    /********** End Relations *********/

    // BOOT
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($model) {
            Log::create([
                "category" => "Vehiculos",
                "action" => "Se creó el vehiculo " . $model->license_plate,
                "user_id" => Auth::id()
            ]);

        });

        static::updated(function($model) {

            Log::create([
                "category" => "Vehiculos",
                "action" => "Se actualizó el vehiculo " . $model->license_plate,
                "user_id" => Auth::id()
            ]);

        });

        static::deleted(function($model) {

            Log::create([
                "category" => "Vehiculos",
                "action" => "Se eliminó el vehiculo " . $model->license_plate,
                "user_id" => Auth::id()
            ]);

        });
    }
}
