<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Auth;

class VehicleType extends Model
{
    use HasFactory;

    protected $table = 'vehicle_types';

    protected $fillable = [
        'name',
        'max_weight'
    ];
    /**
     * @var mixed
     */

    /*********** Methods ************/



    /********** End Methods *********/


    /*********** Relations ************/

    public function vehicles(): HasMany
    {
        return $this->hasMany(Vehicle::class);
    }

    /********** End Relations *********/

    // BOOT
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($model) {
            Log::create([
                "category" => "Tipos de Vehiculos",
                "action" => "Se creó el tipo de vehiculo " . $model->name,
                "user_id" => Auth::id()
            ]);

        });

        static::updated(function($model) {

            Log::create([
                "category" => "Tipos de Vehiculos",
                "action" => "Se actualizó el tipo de vehiculo " . $model->name,
                "user_id" => Auth::id()
            ]);

        });

        static::deleted(function($model) {

            Log::create([
                "category" => "Tipos de Vehiculos",
                "action" => "Se eliminó el tipo de vehiculo " . $model->name,
                "user_id" => Auth::id()
            ]);

        });
    }
}
