<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;

class Warehouse extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'warehouses';

    protected $fillable = [
        'name',
        'address',
        'leader_id',
        'warehouse_type_id'
    ];
    /**
     * @var mixed
     */

    /*********** Methods ************/



    /********** End Methods *********/


    /*********** Relations ************/

    public function warehouse_type(): BelongsTo
    {
        return $this->belongsTo(WarehouseType::class);
    }

    public function employees(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(Employee::class);
    }

    public function leader(): BelongsTo
    {
        return $this->belongsTo(Employee::class, 'leader_id', 'id');
    }

    /********** End Relations *********/

    // BOOT
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function($model) {
            Log::create([
                "category" => "Almacenes",
                "action" => "Se creó el almacene " . $model->name,
                "user_id" => Auth::id()
            ]);

        });

        static::updated(function($model) {

            Log::create([
                "category" => "Almacenes",
                "action" => "Se actualizó el almacene " . $model->name,
                "user_id" => Auth::id()
            ]);

        });

        static::deleted(function($model) {

            Log::create([
                "category" => "Almacenes",
                "action" => "Se eliminó el almacene " . $model->name,
                "user_id" => Auth::id()
            ]);

        });
    }
}
